### ISSUE TITLE
Checkbox button is not being marked

### ISSUE THREAD

**Issue by varayal** [c19-rnd-dashboard/c19-rnd-dashboard-ui#75]
Steps to repro:
1- Navigate to https://coviddash.org/
2- Click on Country
3- Type Mexico
4- Click on the checkbox

Actual result: Checkbox is not being marked and ?c=mex is being appended to the URL

See video as a reference https://www.dropbox.com/s/gznwkna54aqp9ll/Screen%20Recording%202020-07-29%20at%2018.15.36.mov?dl=0

**Comment by j10sanders** [comment]
Thanks @varayal - fixed in https://github.com/c19-rnd-dashboard/c19-rnd-dashboard-ui/pull/78
